project:
  type: default
  output-dir: build

bibliography: bibliography/references.bib

format:
  pdf:
    pdf-engine: pdflatex
    documentclass: article
    classoption: [twocolumn]
    papersize: letter
    fontsize: 9pt
    geometry:
      - top=0.75in
      - bottom=0.75in
      - left=0.75in
      - right=0.75in
    linestretch: 1.0
    number-sections: false
    keep-tex: true
    include-in-header:
      text: |
        \usepackage{times}
        \usepackage{authblk}
  docx:
    number-sections: false
  html:
    toc: true
    toc-depth: 2
